- src: https://github.com/idi-ops/ansible-facts
  name: facts

- src: https://github.com/avtar/ansible-secrets
  name: secrets

- src: https://github.com/avtar/ansible-nodejs
  version: remotes/origin/secret-env-vars
  name: nodejs
